In [6]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Sample feature: hours studied
X = np.array([[1], [2], [3], [4], [5]])

# Labels: 0 = fail, 1 = pass
y = np.array([[0], [0], [0], [1], [1]])

# Weights with bias term
weights_with_bias = np.array([[-4], [1]])   # bias = -4, weight = 1
print(weights_with_bias)

# Weights without bias term
weights_no_bias = np.array([[1]])           # just the weight
print(weights_no_bias)

[[-4]
 [ 1]]
[[1]]


In [7]:
# Add bias column of 1s
X_bias = np.c_[np.ones((X.shape[0], 1)), X]
z_with_bias = X_bias @ weights_with_bias
pred_with_bias = sigmoid(z_with_bias)

print(X_bias)
print(z_with_bias)
print(pred_with_bias)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]
[[-3.]
 [-2.]
 [-1.]
 [ 0.]
 [ 1.]]
[[0.04742587]
 [0.11920292]
 [0.26894142]
 [0.5       ]
 [0.73105858]]


In [9]:
z_no_bias = X @ weights_no_bias
pred_no_bias = sigmoid(z_no_bias)

print(z_no_bias)
print(pred_no_bias)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[0.73105858]
 [0.88079708]
 [0.95257413]
 [0.98201379]
 [0.99330715]]
